name: Poll branch releases
on:
  workflow_call:
    inputs:
      branch:
        description: 'App branch'
        type: string
        default: 'main'

    outputs:
      updateRequired:
        description: 'New version found'
        value: ${{ jobs.check-upstream.outputs.update }}
      upstreamVersion:
        description: 'Upstream version'
        value: '${{ jobs.check-upstream.outputs.version }}'

jobs:
  check-upstream:
    name: Check upstream version
    runs-on: ubuntu-latest

    env:
      currentVersion: ${{ inputs.branch == 'main' && format('{0}', vars.RELEASE_VERSION) || format('{0}', vars.PRELEASE_VERSION) }}

    permissions:
      contents: write

    strategy:
      fail-fast: true
      matrix:
        arch: ["amd64"]
        include:
          - arch: amd64
            os: ubuntu-latest

    outputs:
      update: ${{ steps.check_tag.outputs.exists == 'false' }}
      version: '${{ steps.upstream.outputs.version }}'

    steps:
    - name: Get upstream (pre)release
      id: upstream
      run: |
        TAG=$(curl -sL --request GET \
          --url "${{ github.api_url }}/repos/Sonarr/Sonarr/releases" \
          --header "Accept: application/vnd.github+json" \
          --header "Authorization: token ${{ github.token }}" \
          | jq --argjson DEVELOP ${{ inputs.branch == 'develop' }} \
          -r 'map(select(.prerelease==$DEVELOP)) | first | .tag_name')

        echo "version=${TAG//v}" >> $GITHUB_OUTPUT
      env:
        DEVELOP: ${{ inputs.branch == 'develop' }}

    - name: Check if tag exists
      uses: mukunku/tag-exists-action@v1.6.0
      id: check_tag
      with:
        tag: 'v${{ steps.upstream.outputs.version }}'

    - uses: actions/checkout@v4
      if: steps.check_tag.outputs.exists == 'false'
  
    - name: Update Readme
      uses: jacobtomlinson/gha-find-replace@v3
      if: steps.check_tag.outputs.exists == 'false'
      with:
        find: '${{ env.currentVersion }}'
        replace: '${{ steps.upstream.outputs.version }}'
        include: 'README.md'
        regex: false

    - name: Push changes
      uses: EndBug/add-and-commit@v9
      if: steps.check_tag.outputs.exists == 'false'
      with:
        committer_name: GitHub Actions
        committer_email: actions@github.com
        message: 'docs: Bump ${{ inputs.branch }} image version to ${{ steps.upstream.outputs.version }}'
        tag: 'v${{ steps.upstream.outputs.version }}'