name: New release check
on:
  push:

  # Hourly
  schedule:
    - cron:  '0 * * * *'

  # Manually
  workflow_dispatch:

jobs:
  mainPoll:
    name: 'Poll main branch'
    uses: ./.github/workflows/poll_releases.yml

  mainBuild:
    name: 'Build main branch'
    uses:  ./.github/workflows/build_release.yml
    if: ${{ needs.mainPoll.outputs.updateRequired }}
    needs: 
    - mainPoll
    with:
      existingTag: '${{ needs.mainPoll.outputs.latestTag }}'
      releaseVersion: '${{ needs.mainPoll.outputs.upstreamVersion }}'

  developPoll:
    name: 'Check develop branch'
    uses: ./.github/workflows/poll_releases.yml
    with:
      branch: 'develop'

  developBuild:
    name: 'Build develop branch'
    uses:  ./.github/workflows/build_release.yml
    if: ${{ needs.developPoll.outputs.updateRequired }}
    needs: 
    - developPoll
    with:
      branch: 'develop'
      existingTag: '${{ needs.developPoll.outputs.latestTag }}'
      releaseVersion: '${{ needs.developPoll.outputs.upstreamVersion }}'